name: Create and Deploy

on:
  push:
    branches:
      - master
env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  create-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          sleep 20
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.HOSTNAME }} '
            # Now we have got access to EC2 and we will start the deploy.
            sudo su -
            sleep 20
            cd /home/ubuntu/
            sleep 20
            
            # Check if the repository is already cloned, if yes, then pull changes, otherwise, clone it.
            if [ -d "/home/ubuntu/wordpress-deployment" ]; then
              cd /home/ubuntu/wordpress-deployment
              git pull
            else
              git clone https://github.com/tanvi-aaic/wordpress-deployment.git 
            fi

            sleep 20
            ls /home/ubuntu/wordpress-deployment/wordpress-code/

            sudo rsync -avu /home/ubuntu/wordpress-deployment/wordpress-code/ /var/www/html/wordpress-code/

            #Mount wp-content/uploads/ 
            
            sudo apt-get install -y nfs-common
            sudo mkdir -p /efs/uploads
            sudo mount -t nfs4 fs-0ca784c580bd723f1.efs.us-east-1.amazonaws.com:/ /efs/uploads
            df -h
            sudo mkdir -p /var/www/html/wp-content/uploads/2023/08
            sudo chown -R www-data:www-data /var/www/html/wp-content/uploads/2023/08
            sudo chmod -R 755 /var/www/html/wp-content/uploads/2023/08
            sudo rsync -avu /var/www/html/wp-content/uploads/2023/08* /efs/uploads/
            sudo umount /efs/uploads
            sudo mount -t nfs4 fs-0ca784c580bd723f1.efs.us-east-1.amazonaws.com:/ /var/www/html/wp-content/uploads/2023/08
            sudo sh -c "echo 'fs-0ca784c580bd723f1.efs.us-east-1.amazonaws.com:/ /var/www/html/wp-content/2023/08 nfs4 defaults 0 0' >> /etc/fstab"
            
            '
