name: Create and Deploy
on:
  push:
    branches:
      - master
jobs:
  create-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          sleep 20
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.HOSTNAME }} '
            # Now we have got access to EC2 and we will start the deploy.
            sudo su -
            sleep 20
            cd /home/ubuntu/ 
            sleep 20
            git clone https://github.com/tanvi-aaic/wordpress-deployment.git
            sleep 20
            ls
            sudo mv /home/ubuntu/wordpress-deployment/wordpress-code /var/www/html/
            sleep 20
            rm -r wordpress-code
          '
