name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  create-and-deploy-instance:
    runs-on: ubuntu-latest
    outputs:
      instance-id: ${{ steps.create-instance.outputs.instance-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Create EC2 instance
        id: create-instance
        run: |
          # The create EC2 instance command here

      - name: Wait for 60 seconds
        run: sleep 60

      - name: Get instance ID
        run: echo "Instance ID: ${{ needs.create-instance.outputs.instance-id }}"  # For debugging purposes

      - name: Get instance IP address
        id: get-instance-ip
        run: |
          # Get the instance IP address here

      # Rest of the steps remain unchanged...

      - name: Install httpd on EC2 instance
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          USER_NAME: ubuntu
        run: |
          # Install httpd and PHP modules on the EC2 instance using SSH

